///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class HasiModel {
/*
{
  "id": "1",
  "clientNames": "enock menston",
  "phoneNumber": "07893",
  "CT_munda": "23",
  "LP_mumatako": "23",
  "CC_ibibero": "1",
  "LT_uburebure": "23",
  "CJ_mumavi": "23",
  "TB_mukirenge": "23",
  "updatedOn": "2023-06-10 23:30:15",
  "activeStatus": "1",
  "umudozi_ID": "1"
} 
*/
  String? id;
  String? clientNames;
  String? phoneNumber;
  String? CTMunda;
  String? LPMumatako;
  String? CCIbibero;
  String? LTUburebure;
  String? CJMumavi;
  String? TBMukirenge;
  String? activeStatus;
  String? umudoziID;

  HasiModel({
    this.id,
    this.clientNames,
    this.phoneNumber,
    this.CTMunda,
    this.LPMumatako,
    this.CCIbibero,
    this.LTUburebure,
    this.CJMumavi,
    this.TBMukirenge,
    this.activeStatus,
    this.umudoziID,
  });
  HasiModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    clientNames = json['clientNames']?.toString();
    phoneNumber = json['phoneNumber']?.toString();
    CTMunda = json['CT_munda']?.toString();
    LPMumatako = json['LP_mumatako']?.toString();
    CCIbibero = json['CC_ibibero']?.toString();
    LTUburebure = json['LT_uburebure']?.toString();
    CJMumavi = json['CJ_mumavi']?.toString();
    TBMukirenge = json['TB_mukirenge']?.toString();
    activeStatus = json['activeStatus']?.toString();
    umudoziID = json['umudozi_ID']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['clientNames'] = clientNames;
    data['phoneNumber'] = phoneNumber;
    data['CT_munda'] = CTMunda;
    data['LP_mumatako'] = LPMumatako;
    data['CC_ibibero'] = CCIbibero;
    data['LT_uburebure'] = LTUburebure;
    data['CJ_mumavi'] = CJMumavi;
    data['TB_mukirenge'] = TBMukirenge;
    data['activeStatus'] = activeStatus;
    data['umudozi_ID'] = umudoziID;
    return data;
  }
}
