///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class HejuruModel {
/*
{
  "id": "2",
  "clientNames": "Mugisha",
  "phoneNumber": "0783982872",
  "EP_ibitugu": "1",
  "LP_igituza": "1",
  "LT_uburebure": "1",
  "LM_amaboko": "1",
  "CM_Igikonjo": "1",
  "CT_munda": "1",
  "CB_CH_Amatako": "1",
  "activeStatus": "1",
  "ubudoziID": "1"
} 
*/

  String? id;
  String? clientNames;
  String? phoneNumber;
  String? EPIbitugu;
  String? LPIgituza;
  String? LTUburebure;
  String? LMAmaboko;
  String? CMIgikonjo;
  String? CTMunda;
  String? CBCHAmatako;
  String? ubudoziID;

  HejuruModel({
    this.id,
    this.clientNames,
    this.phoneNumber,
    this.EPIbitugu,
    this.LPIgituza,
    this.LTUburebure,
    this.LMAmaboko,
    this.CMIgikonjo,
    this.CTMunda,
    this.CBCHAmatako,
    this.ubudoziID,
  });
  HejuruModel.fromJson(Map<String, dynamic> json) {
    clientNames = json['clientNames']?.toString();
    phoneNumber = json['phoneNumber']?.toString();
    EPIbitugu = json['EP_ibitugu']?.toString();
    LPIgituza = json['LP_igituza']?.toString();
    LTUburebure = json['LT_uburebure']?.toString();
    LMAmaboko = json['LM_amaboko']?.toString();
    CMIgikonjo = json['CM_Igikonjo']?.toString();
    CTMunda = json['CT_munda']?.toString();
    CBCHAmatako = json['CB_CH_Amatako']?.toString();
    ubudoziID = json['ubudoziID']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['clientNames'] = clientNames;
    data['phoneNumber'] = phoneNumber;
    data['EP_ibitugu'] = EPIbitugu;
    data['LP_igituza'] = LPIgituza;
    data['LT_uburebure'] = LTUburebure;
    data['LM_amaboko'] = LMAmaboko;
    data['CM_Igikonjo'] = CMIgikonjo;
    data['CT_munda'] = CTMunda;
    data['CB_CH_Amatako'] = CBCHAmatako;
    data['ubudoziID'] = ubudoziID;
    return data;
  }
}
